name: Build and Deploy to S3 with CloudFront Invalidation

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-2
  S3_BUCKET: sobaii-react-web-app
  CLOUDFRONT_DISTRIBUTION_ID: ECB00V9P9MRGB

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build project
        env:
          VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
          VITE_FRONTEND_URL: ${{ secrets.VITE_FRONTEND_URL }}
        run: |
          npm install
          npm run build

      - name: Sync build files to S3
        run: |
          aws s3 sync ./dist s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"